variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
   - export PATH=/usr/lib64/ccache:$PATH
   - export LD_LIBRARY_PATH="/usr/local/lib/:/usr/local/lib64/"
   - sed -i 's/3500/7200/g' programs/build_helpers/build_for_cache # 120 
minutes max
   - sed -i 's/3500/7200/g' programs/build_helpers/build_and_test  # 120 
minutes max

Build binaries and run tests:
   stage: build
   script:
      - programs/build_helpers/build_for_cache
      - programs/build_helpers/build_and_test
#     - lcov -d libraries -c -o coverage.info
#     - lcov -r coverage.info */c++/* */boost/* */libraries/fc/* 
*/usr/include/* -o coverageFiltered.info
#     - lcov --list coverageFiltered.info
#   coverage: '/Total:\|\s*([0-9.]+%)\s.*$/
